### ISSUE TITLE
关于数据处理的问题

### ISSUE THREAD

**Issue by linnnn1** [Scallions/ClassSR_paddle#2]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 68, in default_collate_fn
    return {
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 69, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/collate.py", line 61, in default_collate_fn
    return layers.stack(batch, axis=0)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 10397, in stack
    return _C_ops.stack(x, 'axis', axis)
ValueError: (InvalidArgument) Dims of all Inputs(X) must be the same, but received input 1 dim is:3, 0, 0 not equal to input 0 dim:3, 128, 0.
  [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:3, 0, 0 != input_dims[0]:3, 128, 0.] (at /paddle/paddle/phi/infermeta/multiary.cc:1803)
  [operator < stack > error]

请问这样的问题应该怎么解决

**Comment by Scallions** [comment]
看日志是输入的形状不匹配，128和0，检查一下输入看看
